<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
	</array>
	<key>name</key>
	<string>Preview Syntax Colours</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comment.line</string>
			<key>match</key>
			<string>comment\.line</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>constant\.numeric</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.name</string>
			<key>match</key>
			<string>entity\.name</string>
			<key>name</key>
			<string>entity.name</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>invalid.illegal</string>
			<key>match</key>
			<string>invalid\.illegal</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>invalid.deprecated</string>
			<key>match</key>
			<string>invalid\.deprecated</string>
			<key>name</key>
			<string>invalid.deprecated</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword.control</string>
			<key>match</key>
			<string>keyword\.control</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword.operator</string>
			<key>match</key>
			<string>keyword\.operator</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword.other</string>
			<key>match</key>
			<string>keyword\.other</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.underline.link</string>
			<key>match</key>
			<string>markup\.underline\.link</string>
			<key>name</key>
			<string>markup.underline.link</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.underline</string>
			<key>match</key>
			<string>markup\.underline</string>
			<key>name</key>
			<string>markup.underline</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.bold</string>
			<key>match</key>
			<string>markup\.bold</string>
			<key>name</key>
			<string>markup.bold</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.heading</string>
			<key>match</key>
			<string>markup\.heading</string>
			<key>name</key>
			<string>markup.heading</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.italic</string>
			<key>match</key>
			<string>markup\.italic</string>
			<key>name</key>
			<string>markup.italic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.list.numbered</string>
			<key>match</key>
			<string>markup\.list\.numbered</string>
			<key>name</key>
			<string>markup.list.numbered</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.list.unnumbered</string>
			<key>match</key>
			<string>markup\.list\.unnumbered</string>
			<key>name</key>
			<string>markup.list.unnumbered</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.list</string>
			<key>match</key>
			<string>markup\.list</string>
			<key>name</key>
			<string>markup.list</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.quote</string>
			<key>match</key>
			<string>markup\.quote</string>
			<key>name</key>
			<string>markup.quote</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.raw</string>
			<key>match</key>
			<string>markup\.raw</string>
			<key>name</key>
			<string>markup.raw</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.other</string>
			<key>match</key>
			<string>markup\.other</string>
			<key>name</key>
			<string>markup.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>meta</string>
			<key>match</key>
			<string>\'meta'</string>
			<key>name</key>
			<string>meta</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>storage.type</string>
			<key>match</key>
			<string>storage\.type</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>storage.modifier</string>
			<key>match</key>
			<string>storage\.modifier</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted.single</string>
			<key>match</key>
			<string>string\.quoted\.single</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted.double</string>
			<key>match</key>
			<string>string\.quoted\.double</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted.triple</string>
			<key>match</key>
			<string>string\.quoted\.triple</string>
			<key>name</key>
			<string>string.quoted.triple</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted.other</string>
			<key>match</key>
			<string>string\.quoted\.other</string>
			<key>name</key>
			<string>string.quoted.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted</string>
			<key>match</key>
			<string>string\.quoted</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.unquoted</string>
			<key>match</key>
			<string>string\.unquoted</string>
			<key>name</key>
			<string>string.unquoted</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.interpolated</string>
			<key>match</key>
			<string>string\.interpolated</string>
			<key>name</key>
			<string>string.interpolated</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.regexp</string>
			<key>match</key>
			<string>string\.regexp</string>
			<key>name</key>
			<string>string.regexp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.other</string>
			<key>match</key>
			<string>string\.other</string>
			<key>name</key>
			<string>string.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.function</string>
			<key>match</key>
			<string>support\.function</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.class</string>
			<key>match</key>
			<string>support\.class</string>
			<key>name</key>
			<string>support.class</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.type</string>
			<key>match</key>
			<string>support\.type</string>
			<key>name</key>
			<string>support.type</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.constant</string>
			<key>match</key>
			<string>support\.constant</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.variable</string>
			<key>match</key>
			<string>support\.variable</string>
			<key>name</key>
			<string>support.variable</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.other</string>
			<key>match</key>
			<string>support\.other</string>
			<key>name</key>
			<string>support.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable.parameter</string>
			<key>match</key>
			<string>variable\.parameter</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable.language</string>
			<key>match</key>
			<string>variable\.language</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable.other</string>
			<key>match</key>
			<string>variable\.other</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.preview_syntax_colours</string>
	<key>uuid</key>
	<string>c6cc584b-cf71-4176-a646-319cd88e1618</string>
</dict>
</plist>
